# Generated by Django 5.0.6 on 2024-06-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('b_title', models.CharField(max_length=300)),
                ('b_author', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
