# Generated by Django 5.0.6 on 2024-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
